# Generated by Django 5.0.5 on 2024-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
